// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFsh-leIdL7juXIfiqb4hwPkDe7-dmSY',
    appId: '1:119318917245:web:c850c12b65aabb69a80114',
    messagingSenderId: '119318917245',
    projectId: 'my-fitness-app-e9a7c',
    authDomain: 'my-fitness-app-e9a7c.firebaseapp.com',
    storageBucket: 'my-fitness-app-e9a7c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DuGXAdbH3awS--E9l2yQCTGU7OyHXqs',
    appId: '1:119318917245:android:ad9d4aa8f4043b2ca80114',
    messagingSenderId: '119318917245',
    projectId: 'my-fitness-app-e9a7c',
    storageBucket: 'my-fitness-app-e9a7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB83qfhvgVA-Tp86BTxxty4uWPJqpNwMmA',
    appId: '1:119318917245:ios:90bd92f87397a56ea80114',
    messagingSenderId: '119318917245',
    projectId: 'my-fitness-app-e9a7c',
    storageBucket: 'my-fitness-app-e9a7c.appspot.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
